# Site settings
title: Andrew Mowe
email: andrewmowe@gmail.com
url: https://mowe.money
description: "Andrew Mowe is a funky fresh Frond End Developer with swagger coming out his ears."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Andrew Mowe
  location: Location
  social: Social
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/andrewmowe
  - title: github
    url: http://github.com/andrewmowe

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Andrew Mowe: Front End Dev to the stars'

# Build settings
markdown: kramdown
permalink: pretty
